require "./open_file.rb"
require "./endings.rb"
require "yaml"

# XXX/ Этот код необходим только при использовании русских букв (http://ruby.qkspace.com/windows-problema-s-kodirovkoy-russkimi-bukvami)
if (Gem.win_platform?)
  Encoding.default_external = Encoding.find(Encoding.locale_charmap)
  Encoding.default_internal = __ENCODING__

  [$stdin, $stdout].each do |io|
    io.set_encoding(Encoding.default_external, Encoding.default_internal)
  end
end

raper = OpenFile.new
empty_hash = {}
allDataBattles = raper.getHash("(Pra(Killa'Gramm) против Obe 1 Kanobe (VERSUS_MAIN EVENT СЕЗОН 2)", "Pra(Killa'Gramm)", empty_hash)
allDataBattles = raper.getHash("13_47 против Лехи Медь (VERSUS BATTLE СЕЗОН 4)", "13_47", allDataBattles)
allDataBattles = raper.getHash("1917 против Palmdropov (VERSUS FRESH BLOOD 4) Отбор", "1917", allDataBattles)
allDataBattles = raper.getHash("Артем Лоик против ГИГА (RAP SOX BATTLE)", "Артем Лоик", allDataBattles)
allDataBattles = raper.getHash("Артем Лоик против Galat (VERSUS BATTLE СЕЗОН 3)", "Артем Лоик", allDataBattles)
allDataBattles = raper.getHash("Артема Лоика против Хохла (VERSUS BATTLE СЕЗОН 2)", "Артем Лоик", allDataBattles)
allDataBattles = raper.getHash("Артема Татищевского против Три Ко Пюшона (VERSUS BATTLE СЕЗОН 2)", "Артем Татищевский", allDataBattles)
allDataBattles = raper.getHash("Басота против Meowizzy (VERSUS BATTLE СЕЗОН 1)", "Басота", allDataBattles)
allDataBattles = raper.getHash("Басоты против Drago (VERSUS BETTLE СЕЗОН 2)", "Басота", allDataBattles)
allDataBattles = raper.getHash("Браги против Микси (VERSUS_ FRESH BLOOD 4) Этап 1", "Браги", allDataBattles)
allDataBattles = raper.getHash("Браги против OBJECT (VERSUS FRESH BLOOD 4) Отбор", "Браги", allDataBattles)
allDataBattles = raper.getHash("Брол против Just (VERSUS BATTLE СЕЗОН 1)", "Брол", allDataBattles)
allDataBattles = raper.getHash("Брол VS Rokki Roketto (VERSUS BETTLE СЕЗОН 2)", "Брол", allDataBattles)
allDataBattles = raper.getHash("Букер против Млечного (VERSUS FRESH BLOOD 2)", "Букер", allDataBattles)
allDataBattles = raper.getHash("Букер против ХХОС (VERSUS FRESH BLOOD 2)", "Букер", allDataBattles)
allDataBattles = raper.getHash("Букера против Замая (VERSUS BPM)", "Букер", allDataBattles)
allDataBattles = raper.getHash("Букера против Rickey F (VERSUS FRESH BLOOD 2)", "Букер", allDataBattles)
allDataBattles = raper.getHash("Вити Classic'a  против Хохла (VERSUS_ MAIN EVENT 2)", "Витя Classic", allDataBattles)
allDataBattles = raper.getHash("Витя CLassic против СД (VERSUS BPM)", "Витя Classic", allDataBattles)
allDataBattles = raper.getHash("Витя Classic против MickeyMouse (VERSUS BPM)", "Витя Classic", allDataBattles)
allDataBattles = raper.getHash("Галата против Хохла (VERSUS BATTLE СЕЗОН 1)", "Галата", allDataBattles)
allDataBattles = raper.getHash("Гарри Топор против Billy Milligan'а  (VERSUS BATTLE СЕЗОН 1)", "Гарри Топор", allDataBattles)
allDataBattles = raper.getHash("Гарри Топор против Rickey F (VERSUS BPM)", "Гарри Топор", allDataBattles)
allDataBattles = raper.getHash("Гарри Топора против Типси Типа (VERSUS BATTLE СЕЗОН 3)", "Гарри Топор", allDataBattles)
allDataBattles = raper.getHash("Гарри Топора против CZAR (VERSUS BATTLE СЕЗОН 1)", "Гарри Топор", allDataBattles)
allDataBattles = raper.getHash("Гарри Топора против Noiza MC (VERSUS BATTLE СЕЗОН 1)", "Гарри Топор", allDataBattles)
allDataBattles = raper.getHash("Гарри Топора против ST (VERSUS BATTLE СЕЗОН 2)", "Гарри Топор", allDataBattles)
allDataBattles = raper.getHash("ГИГА  против Артем Лоик (RAP SOX BATTLE)", "ГИГА", allDataBattles)
allDataBattles = raper.getHash("Гнойный против Эрнесто Заткнитесь (SLOVOSPB VS VERSUS)", "Гнойный", allDataBattles)
allDataBattles = raper.getHash("Гнойный aka Слава КПСС VS Oxxxymiron (VERSUS VS SLOVOSPB)", "Гнойный", allDataBattles)
allDataBattles = raper.getHash("Грязный Рамирес против Энди Картрайт (VERSUS BATTLE СЕЗОН 4)", "Грязный Рамирес", allDataBattles)
allDataBattles = raper.getHash("Джарахов против Ларина (VERSUS BPM)", "Джарахов", allDataBattles)
allDataBattles = raper.getHash("Дима Гамбит против Obe 1 Kanobe  (VERSUS BETTLE СЕЗОН 2)", "Дима Гамбит", allDataBattles)
allDataBattles = raper.getHash("Династ против Miles (VERSUS FRESH BLOOD 4) Этап 1", "Династ", allDataBattles)
allDataBattles = raper.getHash("Династ против Paragrin (VERSUS FRESH BLOOD 4) Отбор", "Династ", allDataBattles)
allDataBattles = raper.getHash("Дуни против Oxxxymirona (VERSUS_MAIN EVENT 2)", "Дуня", allDataBattles)
allDataBattles = raper.getHash("Заебатсу против Илья Мирный (SLOVOSPB VS VERSUS)", "Заебатсу", allDataBattles)
allDataBattles = raper.getHash("Дуня против Кореш (VERSUS BATTLE СЕЗОН 3)", "Дуня", allDataBattles)
allDataBattles = raper.getHash("Замай против СД (VERSUS BATTLE СЕЗОН 4)", "Замая", allDataBattles)
allDataBattles = raper.getHash("Замая против Букера  (VERSUS BPM)", "Замая", allDataBattles)
allDataBattles = raper.getHash("Ильи Мирного против Эрнесто Заткнитесь (VERSUS_ FRESH BLOOD)", "Илья Мирный", allDataBattles)
allDataBattles = raper.getHash("Ильи Мирного vs Mytee Dee (VERSUS_ FRESH BLOOD)", "Илья Мирный", allDataBattles)
allDataBattles = raper.getHash("Казанский против Sector (VERSUS FRESH BLOOD 4) Отбор", "Казанский", allDataBattles)
allDataBattles = raper.getHash("Кореш против Дуня (VERSUS BATTLE СЕЗОН 3)", "Кореш", allDataBattles)
allDataBattles = raper.getHash("Крип-А-Крип против Billy Milligan (VERSUS_MAIN EVENT СЕЗОН 2)", "Крип-А-Крип", allDataBattles)
allDataBattles = raper.getHash("Крип-А-Крип против Oxxxymiron  (VERSUS BATTLE СЕЗОН 1)", "Крип-А-Крип", allDataBattles)
allDataBattles = raper.getHash("Ларина против Джарахова (VERSUS BPM)", "Ларина", allDataBattles)
allDataBattles = raper.getHash("Ларина против Хованского (VERSUS BATTLE СЕЗОН 3)", "Ларина", allDataBattles)
allDataBattles = raper.getHash("Леха Медь против 13_47 (VERSUS BATTLE СЕЗОН 4)", "Леха Медь", allDataBattles)
allDataBattles = raper.getHash("Леха Медь против Эмио Афишл (VERSUS BATTLE СЕЗОН 3)", "Леха Медь", allDataBattles)
allDataBattles = raper.getHash("Леха Медь против Abbalbisk (SLOVOSPB VS VERSUS)", "Леха Медь", allDataBattles)
allDataBattles = raper.getHash("Леши GS против Lodoss (VERSUS_ FRESH BLOOD)", "Леши GS", allDataBattles)
allDataBattles = raper.getHash("Лоика против Ярмака _ RAP BATTLE", "Лоика", allDataBattles)
allDataBattles = raper.getHash("ЛСП против Meowizzy (VERSUS BATTLE СЕЗОН 3)", "ЛСП", allDataBattles)
allDataBattles = raper.getHash("Майти Ди против МЦ Похоронил (VERSUS BATTLE СЕЗОН 4)", "Майти Ди", allDataBattles)
allDataBattles = raper.getHash("Майти Ди против Edik_Kingsta (VERSUS VS SLOVOSPB)", "Майти Ди", allDataBattles)
allDataBattles = raper.getHash("Марины Кацубы против Drago (VERSUS BATTLE СЕЗОН 3)", "Марины Кацубы", allDataBattles)
allDataBattles = raper.getHash("Микси против Браги (VERSUS_ FRESH BLOOD 4) Этап 1", "Микси", allDataBattles)
allDataBattles = raper.getHash("Микси против J.Makonnen (VERSUS FRESH BLOOD 4) Отбор", "Микси", allDataBattles)
allDataBattles = raper.getHash("Млечного против Drago (VERSUS BPM)", "Млечный", allDataBattles)
allDataBattles = raper.getHash("МЦ Похоронил против Сын Проститутки (VERSUS FRESH BLOOD 3)", "МЦ Похоронил", allDataBattles)
allDataBattles = raper.getHash("МЦ Похоронил против Teeraps (VERSUS FRESH BLOOD 3)", "МЦ Похоронил", allDataBattles)
allDataBattles = raper.getHash("Пиэм против N'rage (VERSUS FRESH BLOOD 4) Этап 1", "Пиэм", allDataBattles)
allDataBattles = raper.getHash("Подземный Принц (Хатт) против Jubilee (VERSUS BATTLE СЕЗОН 1)", "Подземный Принц (Хатт)", allDataBattles)
allDataBattles = raper.getHash("Птаха против Guf (VERSUS BATTLE СЕЗОН 4)", "Птаха", allDataBattles)
allDataBattles = raper.getHash("Саморез & МС MoonStar против John rai & Xoxoл (VERSUS BATTLE СЕЗОН 1)", "Саморез & МС MoonStar", allDataBattles)
allDataBattles = raper.getHash("Саша Скул против John Rai (VERSUS BETTLE СЕЗОН 2)", "Саша Скул", allDataBattles)
allDataBattles = raper.getHash("СД  против Замай (VERSUS BATTLE СЕЗОН 4)", "СД", allDataBattles)
allDataBattles = raper.getHash("СД  против Johnyboy (VERSUS BATTLE СЕЗОН 1)", "СД", allDataBattles)
allDataBattles = raper.getHash("СД против Витя CLassic (VERSUS BPM)", "СД", allDataBattles)
allDataBattles = raper.getHash("СД против Хайда (VERSUS BATTLE СЕЗОН 1)", "СД", allDataBattles)
allDataBattles = raper.getHash("СД против Chet'а (VERSUS_ MAIN EVETN СЕЗОН 2)", "СД", allDataBattles)
allDataBattles = raper.getHash("Соня Мармеладова aka Гнойный против Rickey F (VERSUS BPM)", "Соня Мармеладова aka Гнойный", allDataBattles)
allDataBattles = raper.getHash("Сын Проститутки против МЦ Похоронил (VERSUS FRESH BLOOD 3)", "Сын Проститутки", allDataBattles)
allDataBattles = raper.getHash("Сявы против Lil Dik (VERSUS BATTLE СЕЗОН 4)", "Сявы", allDataBattles)
allDataBattles = raper.getHash("Типси Типа против Гарри Топора  (VERSUS BATTLE СЕЗОН 3)", "Типси Типа", allDataBattles)
allDataBattles = raper.getHash("Тот самый Коля против Эрнесто Заткнитесь (VERSUS BATTLE СЕЗОН 1)", "Тот самый Коля", allDataBattles)
allDataBattles = raper.getHash("Хайда против СД (VERSUS BATTLE СЕЗОН 1)", "Хайда", allDataBattles)
allDataBattles = raper.getHash("Хип-хоп одинокой старухи против Д. Фреда (VERSUS FRESH BLOOD 2)", "Хип-хоп одинокой старухи", allDataBattles)
allDataBattles = raper.getHash("Хованского против Ларина (VERSUS BATTLE СЕЗОН 3)", "Хованский", allDataBattles)
allDataBattles = raper.getHash("Хохла против Артема Лоика (VERSUS BATTLE СЕЗОН 2)", "Хохла", allDataBattles)
allDataBattles = raper.getHash("Хохла против Вити Classic'a (VERSUS_ MAIN EVENT 2)", "Хохла", allDataBattles)
allDataBattles = raper.getHash("Хохла против Галата (VERSUS BATTLE СЕЗОН 1)", "Хохла", allDataBattles)
allDataBattles = raper.getHash("ХХОС против Alphavite (VERSUS BPM)", "ХХОС",allDataBattles)
allDataBattles = raper.getHash("ХХОС против Rickey F (VERSUS FRESH BLOOD 2)", "ХХОС", allDataBattles)
allDataBattles = raper.getHash("Электромышь против Teeraps (VERSUS FRESH BLOOD 3)", "Электромышь", allDataBattles)
allDataBattles = raper.getHash("Электромышь против tvoigreh (VERSUS FRESH BLOOD 3)", "Электромышь", allDataBattles)
allDataBattles = raper.getHash("Эль против Punkteer (VERSUS FRESH BLOOD 4) Отбор", "Эль", allDataBattles)
allDataBattles = raper.getHash("Эмио Афишл против Леха Медь (VERSUS BATTLE СЕЗОН 3)", "Эмио Афишл", allDataBattles)
allDataBattles = raper.getHash("Эмио Афишл против Giga 1 (VERSUS BPM)", "Эмио Афишл", allDataBattles)
allDataBattles = raper.getHash("Энди Картрайт против Грязный Рамирес (VERSUS BATTLE СЕЗОН 4)", "Энди Картрайт", allDataBattles)
allDataBattles = raper.getHash("Энди Картрайт против ATL (VERSUS BATTLE СЕЗОН 1)", "Энди Картрайт", allDataBattles)
allDataBattles = raper.getHash("Эрнесто Заткнитесь против Гнойного (SLOVOSPB VS VERSUS)", "Эрнесто Заткнитесь", allDataBattles)
allDataBattles = raper.getHash("Эрнесто Заткнитесь против Ильи Мирного (VERSUS_ FRESH BLOOD)", "Эрнесто Заткнитесь", allDataBattles)
allDataBattles = raper.getHash("Эрнесто Заткнитесь против Тот самый Коля (VERSUS BATTLE СЕЗОН 1)", "Эрнесто Заткнитесь", allDataBattles)
allDataBattles = raper.getHash("Эрнесто Заткнитесь против Alphavit'a  (VERSUS_ FRESH BLOOD)", "Эрнесто Заткнитесь", allDataBattles)
allDataBattles = raper.getHash("Эрнесто Заткнитесь VS Mytee Dee (VERSUS_ FRESH BLOOD)", "Эрнесто Заткнитесь", allDataBattles)
allDataBattles = raper.getHash("Ярмак против Артема Лоика _ RAP BATTLE", "Ярмак", allDataBattles)
allDataBattles = raper.getHash("D.Masta против ST (VERSUS ALL STARS)", "D.Masta", allDataBattles)
allDataBattles = raper.getHash("Abbalbisk  против Леха Медь (SLOVOSPB VS VERSUS)", "Abbalbisk", allDataBattles)
allDataBattles = raper.getHash("Alphavite против ХХОС (VERSUS BPM)", "Alphavite", allDataBattles)
allDataBattles = raper.getHash("Alphavite против Mytee Dee (VERSUS_ FRESH BLOOD)", "Alphavite", allDataBattles)
allDataBattles = raper.getHash("ATL против Энди Картрайт (VERSUS BATTLE СЕЗОН 1)", "ATL", allDataBattles)
allDataBattles = raper.getHash("Bes против Meowizzy (VERSUS_MAIN EVENT СЕЗОН 1)", "Bes", allDataBattles)
allDataBattles = raper.getHash("Billy Milligan'а против Гарри Топора  (VERSUS BATTLE СЕЗОН 1)", "Billy Milligan'а", allDataBattles)
allDataBattles = raper.getHash("Billy Milligan против Крип-А-Крип (VERSUS_MAIN EVENT СЕЗОН 2)", "Billy Milligan'а", allDataBattles)
allDataBattles = raper.getHash("Chet'а против СД (VERSUS_ MAIN EVETN СЕЗОН 2)", "Chet'а", allDataBattles)
allDataBattles = raper.getHash("CZAR против Гарри Топора (VERSUS BATTLE СЕЗОН 1)", "CZAR", allDataBattles)
allDataBattles = raper.getHash("Dizaster против Oxxxymirona (KOTD) _ RUS", "Dizaster", allDataBattles)
allDataBattles = raper.getHash("Dom1no против Walkie (VERSUS BPM)", "Dom1no", allDataBattles)
allDataBattles = raper.getHash("Drago против Басоты (VERSUS BETTLE СЕЗОН 2)", "Drago", allDataBattles)
allDataBattles = raper.getHash("Drago против Марины Кацубы (VERSUS BATTLE СЕЗОН 3)", "Drago", allDataBattles)
allDataBattles = raper.getHash("Drago против Млечного (VERSUS BPM)", "Drago",allDataBattles)
allDataBattles = raper.getHash("Drago против Юли KIWI (VERSUS VS SLOVOSPB)", "Drago", allDataBattles)
allDataBattles = raper.getHash("Drago против MC No Limit (VERSUS BPM)", "Drago", allDataBattles)
allDataBattles = raper.getHash("Drago против Mufasah (VERSUS BPM)", "Drago", allDataBattles)
allDataBattles = raper.getHash("Edik_Kingsta против Майти Ди (SLOVOSPB VS VERSUS)", "Edik_Kingsta", allDataBattles)
allDataBattles = raper.getHash("Galat  против Yanix (VERSUS BATTLE СЕЗОН 1)", "Галата", allDataBattles)
allDataBattles = raper.getHash("Galat против Артем Лоик (VERSUS BATTLE СЕЗОН 3)", "Галата", allDataBattles)
allDataBattles = raper.getHash("Galat против Mozee Montana (VERSUS BPM)", "Галата", allDataBattles)
allDataBattles = raper.getHash("Galata против D.Masta (VERSUS BATTLE СЕЗОН 3)", "Галата", allDataBattles)
allDataBattles = raper.getHash("Giga 1 против Эмио Афишл (VERSUS BPM)", "ГИГА", allDataBattles)
allDataBattles = raper.getHash("Guf против Птаха (VERSUS BATTLE СЕЗОН 4)", "Guf", allDataBattles)
allDataBattles = raper.getHash("Heavy против Ruskey (VERSUS BATTLE СЕЗОН 1)", "Heavy", allDataBattles)
allDataBattles = raper.getHash("I1 против Meowizzy (VERSUS BATTLE СЕЗОН 1)", "I1", allDataBattles)
allDataBattles = raper.getHash("J.Makonnen против Микси (VERSUS FRESH BLOOD 4) Отбор", "J.Makonnen", allDataBattles)
allDataBattles = raper.getHash("J.Makonnen против Paragrin (VERSUS FRESH BLOOD 4) Этап 1", "J.Makonnen", allDataBattles)
allDataBattles = raper.getHash("John rai & Xoxoл против Саморез & МС MoonStar (VERSUS BATTLE СЕЗОН 1)", "John rai & Xoxoл", allDataBattles)
allDataBattles = raper.getHash("John Rai против Саша Скул (VERSUS BETTLE СЕЗОН 2)", "John Rai", allDataBattles)
allDataBattles = raper.getHash("Johnyboy против СД (VERSUS BATTLE СЕЗОН 1)", "Johnyboy", allDataBattles)
allDataBattles = raper.getHash("Johnyboy против Jubilee (VERSUS BETTLE СЕЗОН 2)", "Johnyboy", allDataBattles)
allDataBattles = raper.getHash("Johnyboy'a против Oxxxymiron'a (VERSUS BATTLE СЕЗОН 3)", "Johnyboy", allDataBattles)
allDataBattles = raper.getHash("Jubilee против Подземный Принц (Хатт) (VERSUS BATTLE СЕЗОН 1)", "Jubilee", allDataBattles)
allDataBattles = raper.getHash("Jubille против Johnyboy  (VERSUS BETTLE  СЕЗОН 2)", "Jubilee", allDataBattles)
allDataBattles = raper.getHash("Just против Брола (VERSUS BATTLE СЕЗОН 1)", "Just", allDataBattles)
allDataBattles = raper.getHash("LeTai против N'rage (VERSUS FRESH BLOOD 4) Отбор", "LeTai", allDataBattles)
allDataBattles = raper.getHash("LeTai против Sawyer (VERSUS FRESH BLOOD 4) Этап 1", "LeTai", allDataBattles)
allDataBattles = raper.getHash("Lil Dik против Сявы (VERSUS BATTLE СЕЗОН 4)", "Lil Dik", allDataBattles)
allDataBattles = raper.getHash("Lodoss против Леши GS  (VERSUS_ FRESH BLOOD)", "Lodoss", allDataBattles)
allDataBattles = raper.getHash("MC No Limit против Drago (VERSUS BPM)", "MC No Limit", allDataBattles)
allDataBattles = raper.getHash("Meowizzy против Басота (VERSUS BATTLE СЕЗОН 1)", "Meowizzy", allDataBattles)
allDataBattles = raper.getHash("Meowizzy против ЛСП (VERSUS BATTLE СЕЗОН 3)", "Meowizzy", allDataBattles)
allDataBattles = raper.getHash("Meowizzy против Bes (VERSUS_MAIN EVENT СЕЗОН 1)", "Meowizzy", allDataBattles)
allDataBattles = raper.getHash("Meowizzy против I1 (VERSUS BATTLE СЕЗОН 1)", "Meowizzy", allDataBattles)
allDataBattles = raper.getHash("MickeyMouse против Витя Classic (VERSUS BPM)", "MickeyMouse", allDataBattles)
allDataBattles = raper.getHash("Miles против Sawyer (VERSUS_ FRESH BLOOD 4) Отбор", "Miles", allDataBattles)
allDataBattles = raper.getHash("MoonStara против Narek (VERSUS FRESH BLOOD 2)", "MoonStara", allDataBattles)
allDataBattles = raper.getHash("MoonStara против Sin'a (VERSUS_ FRESH BLOOD 2)", "MoonStara", allDataBattles)
allDataBattles = raper.getHash("Mozee Montana против Галата (VERSUS BPM)", "Mozee Montana", allDataBattles)
allDataBattles = raper.getHash("Mufasah против Drago (VERSUS BPM)", "Mufasah", allDataBattles)
allDataBattles = raper.getHash("Mufasah против Redo (VERSUS BPM)", "Mufasah", allDataBattles)
allDataBattles = raper.getHash("Mytee Dee против Alphavite (VERSUS_ FRESH BLOOD)", "Mytee Dee", allDataBattles)
allDataBattles = raper.getHash("Mytee Dee против Niggarex’а (VERSUS_ FRESH BLOOD)", "Mytee Dee", allDataBattles)
allDataBattles = raper.getHash("Mytee Dee против Pitty (VERSUS_ FRESH BLOOD)", "Mytee Dee", allDataBattles)
allDataBattles = raper.getHash("Mytee Dee vs Ильи Мирного (VERSUS_ FRESH BLOOD)", "Mytee Dee", allDataBattles)
allDataBattles = raper.getHash("Mytee Dee VS Эрнесто Заткнитесь (VERSUS_ FRESH BLOOD)", "Mytee Dee", allDataBattles)
allDataBattles = raper.getHash("N'rage против Пиэм (VERSUS FRESH BLOOD 4) Этап 1", "N'rage", allDataBattles)
allDataBattles = raper.getHash("N'rage против LeTai (VERSUS FRESH BLOOD 4) Отбор", "N'rage", allDataBattles)
allDataBattles = raper.getHash("Niggarex против Mytee Dee (VERSUS_ FRESH BLOOD)", "Niggarex", allDataBattles)
allDataBattles = raper.getHash("Noiza MC против Гарри Топора (VERSUS BATTLE СЕЗОН 1)", "Noiza MC", allDataBattles)
allDataBattles = raper.getHash("Obe 1 Kanobe против (Pra(Killa'Gramm) (VERSUS_MAIN EVENT СЕЗОН 2)", "Obe 1 Kanobe", allDataBattles)
allDataBattles = raper.getHash("Obe 1 Kanobe против (Pra(Killa'Gramm) (VERSUS_MAIN EVENT СЕЗОН 2)", "Obe 1 Kanobe", allDataBattles)
allDataBattles = raper.getHash("Obe 1 Kanobe против Гарри Топор (VERSUS BATTLE СЕЗОН 4)", "Obe 1 Kanobe", allDataBattles)
allDataBattles = raper.getHash("Obe 1 Kanobe против Дима Гамбит (VERSUS BETTLE СЕЗОН 2)", "Obe 1 Kanobe",allDataBattles)
allDataBattles = raper.getHash("OBJECT против Браги (VERSUS FRESH BLOOD 4) Отбор", "OBJECT", allDataBattles)
allDataBattles = raper.getHash("Oxxxymiron против Dizaster (KOTD) _ RUS", "Oxxxymiron", allDataBattles)
allDataBattles = raper.getHash("Oxxxymiron против ST (VERSUS BATTLE СЕЗОН 3)", "Oxxxymiron", allDataBattles)
allDataBattles = raper.getHash("Oxxxymiron VS Гнойный aka Слава КПСС (VERSUS VS SLOVOSPB)", "Oxxxymiron", allDataBattles)
allDataBattles = raper.getHash("Oxxxymiron'a против Крип-А-Крип  (VERSUS BATTLE СЕЗОН 1)", "Oxxxymiron", allDataBattles)
allDataBattles = raper.getHash("Oxxxymirona против Дуни (VERSUS_MAIN EVENT 2)", "Oxxxymiron", allDataBattles)
allDataBattles = raper.getHash("Oxxxymirona против Johnyboy'a (VERSUS BATTLE СЕЗОН 3)", "Oxxxymiron", allDataBattles)

empty_hash = {}

dataCountBadWords = raper.countBadWords("Pra(Killa'Gramm)", allDataBattles, empty_hash)
dataCountBadWords = raper.countBadWords("13_47", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("1917", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Артем Лоик", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Артем Татищевский", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Басота", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Браги", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Брол", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Букер", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Витя Classic", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Галата", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Гарри Топор", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("ГИГА", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Гнойный", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Грязный Рамирес", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Джарахов", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Дима Гамбит", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Династ", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Дуня", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Заебатсу", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Замая", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Илья Мирный", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Казанский", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Кореш", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Крип-А-Крип", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Ларина", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Леха Медь", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Леши GS", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Лоика", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("ЛСП", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Майти Ди", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Марины Кацубы", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Микси", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Млечный", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("МЦ Похоронил", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Пиэм", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Подземный Принц (Хатт)", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Птаха", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Саморез & МС MoonStar", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Саша Скул", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("СД", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Соня Мармеладова aka Гнойный", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Сын Проститутки", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Сявы", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Типси Типа", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Тот самый Коля", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Хайда", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Хип-хоп одинокой старухи", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Хованский", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Хохла", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("ХХОС", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Эль", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Эмио Афишл", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Энди Картрайт", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Эрнесто Заткнитесь", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Ярмак", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("D.Masta", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Abbalbisk", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Alphavite", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("ATL", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Bes", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Billy Milligan'а", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Chet'а", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("CZAR", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Dizaster", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Dom1no", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Drago", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Edik_Kingsta", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Галата", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("ГИГА", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Guf", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Heavy", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("I1", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("J.Makonnen", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("John rai & Xoxoл", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("John Rai", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Johnyboy", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Jubilee", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Just", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("LeTai", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Lil Dik", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Lodoss", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("MC No Limit", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Meowizzy", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("MickeyMouse", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Miles", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("MoonStara", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Mozee Montana", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Mufasah", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Mytee Dee", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("N'rage", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Niggarex", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Noiza MC", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Obe 1 Kanobe", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("OBJECT", allDataBattles, dataCountBadWords)
dataCountBadWords = raper.countBadWords("Oxxxymiron", allDataBattles, dataCountBadWords)

#Сортируем хэш в порядке убывания для последующего вывода данных в консоль
allDataBadWords = dataCountBadWords.sort_by{|_key, value| value}.reverse.to_h

epmtyHash = {}

dataCountBattles = raper.countBattles("Pra(Killa'Gramm)", allDataBattles, empty_hash)
dataCountBattles = raper.countBattles("13_47", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("1917", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Артем Лоик", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Артем Татищевский", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Басота", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Браги", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Брол", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Букер", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Витя Classic", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Галата", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Гарри Топор", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("ГИГА", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Гнойный", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Грязный Рамирес", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Джарахов", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Дима Гамбит", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Династ", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Дуня", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Заебатсу", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Замая", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Илья Мирный", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Казанский", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Кореш", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Крип-А-Крип", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Ларина", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Леха Медь", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Леши GS", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Лоика", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("ЛСП", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Майти Ди", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Марины Кацубы", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Микси", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Млечный", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("МЦ Похоронил", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Пиэм", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Подземный Принц (Хатт)", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Саморез & МС MoonStar", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Саша Скул", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("СД", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Соня Мармеладова aka Гнойный", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Сын Проститутки", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Сявы", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Типси Типа", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Тот самый Коля", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Хайда", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Хип-хоп одинокой старухи", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Хованский", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Хохла", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("ХХОС", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Электромышь", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Эль", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Эмио Афишл", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Эрнесто Заткнитесь", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Ярмак", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("D.Masta", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Abbalbisk", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Alphavite", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("ATL", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Bes", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Billy Milligan'а", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Chet'а", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("CZAR", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Dizaster", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Dom1no", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Drago", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Edik_Kingsta", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Галата", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("ГИГА", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Guf", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Heavy", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("I1", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("J.Makonnen", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("John rai & Xoxoл", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("John Rai", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Johnyboy", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Jubilee", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Just", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("LeTai", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Lil Dik", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Lodoss", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("MC No Limit", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Meowizzy", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("MickeyMouse", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Miles", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("MoonStara", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Mozee Montana", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Mufasah", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Mytee Dee", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("N'rage", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Niggarex", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Noiza MC", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Obe 1 Kanobe", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("OBJECT", allDataBattles, dataCountBattles)
dataCountBattles = raper.countBattles("Oxxxymiron", allDataBattles, dataCountBattles)

firstParameter = ARGV.first
countWords = ARGV[1].to_i
rapperName = ARGV.last

case firstParameter
when "--top-bad-words"
  if dataCountBattles.size >= countWords
    countOutput = allDataBadWords.first(countWords)
    countOutput.each {|rapperName, countBadWords|
                  ending = EndingGenerate.new
                  countOfBattles = dataCountBattles[rapperName]
                  countOfBattles ||= 1
                  countOfBadWordsOnBattle = countBadWords.to_f/countOfBattles
                  get_countWordsInRound = OpenFile.new
                  countWordsInRound = get_countWordsInRound.countBadWords(rapperName, allDataBattles, dataCountBadWords, "countWordsInRound")

                  puts "#{rapperName} | #{countOfBattles} батл#{ending.endingOfBattle(countOfBattles)} |"\
                       "#{countBadWords} #{ending.endingOfBadWord(countBadWords)}  |"\
                       "#{countOfBadWordsOnBattle.round(2)} слова на батл |"\
                       "#{countWordsInRound} слов#{ending.endingOfWord(countWordsInRound)} в раунде"
                      }
  else
    puts "У в этой базе  нет столько рэперов :("
  end
  when  "--top-words"
    if dataCountBattles.key?(rapperName)
      dateOfRepeatWords = raper.countRepeatWords(allDataBattles, rapperName)
        if countWords > dateOfRepeatWords.size
          puts "Слишком большое число"
        else
          countOutput = dateOfRepeatWords.first(countWords)
          countOutput.each{|word, countRepeat|
                      puts "#{word.capitalize} - #{countRepeat}"
                         }
        end
    else
      puts "Репер #{rapperName} не известен мне. Зато мне известны:"
      sleep 1
      countOutput = allDataBadWords.first(3)
      countOutput.each_key{|rapperName|
      puts "#{rapperName}"}
    end
end
